version: "3"
services:
  shopwep-backend:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./target/Shop-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war/
    # restart: unless-stopped
